### PR TITLE
Add license and notice

### PR DESCRIPTION
**Pull request by CBarraford**
Fixes https://github.com/rstudio/redx/issues/23

### CODE REVIEW

**Comment by prologic** [comment]
And what is the actual license of redx here? MIT or something else?

**Comment by CBarraford** [comment]
@prologic https://opensource.org/licenses/BSD-2-Clause

**Comment by prologic** [comment]
Let's put this in the README so it's obvious?

**Comment by CBarraford** [comment]
@prologic its common practice to put it in its own file (makes it easier to see historic changes). And id rather avoid putting it in two places.

https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository

**Comment by prologic** [comment]
No I mean the 2-clause BSD part :) Not the actual contents of the `LICENSE` file :)

**Comment by CBarraford** [comment]
@prologic oh, gotcha. That we can do.

**Comment by prologic** [comment]
For example it's common practice to indicate the License type in some
metadata somewhere; e.g (if this was a Python project):
https://pypi.python.org/pypi/autodock


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
:+1: :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Pull request merged**
